export {default as Cart}  from './Cart'
export { default as Menu } from './Menu'
export { default as Notebook } from './Notebook'
export { default as Search } from './Search'
export { default as User } from './User'
export { default as Facebook } from './FacebookIcon'
export { default as Instagram } from './InstagramIcon'
export { default as Tiktok } from './TikTokIcon'
export { default as Youtube } from './YoutubeIcon'
export { default as Selo1 } from './Selo1'
export { default as Selo2 } from './Selo2'
export { default as PaymentMehod } from './PaymentMehod'